import os
import httpx
from typing import Dict, List


class LLMService:
    def __init__(self):
        self.anthropic_key = os.getenv("ANTHROPIC_API_KEY")
        self.openai_key = os.getenv("OPENAI_API_KEY")

    async def generate_with_claude(self, prompt: str, max_tokens: int = 2000) -> str:
        if not self.anthropic_key or self.anthropic_key == "your-key-here":
            return None
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "https://api.anthropic.com/v1/messages",
                    headers={
                        "x-api-key": self.anthropic_key,
                        "content-type": "application/json",
                        "anthropic-version": "2023-06-01"
                    },
                    json={
                        "model": "claude-3-haiku-20240307",
                        "max_tokens": max_tokens,
                        "messages": [{"role": "user", "content": prompt}]
                    },
                    timeout=60.0
                )
                data = response.json()
                if "content" in data:
                    return data["content"][0]["text"]
                else:
                    print("Claude API error: " + str(data))
                    return None
        except Exception as e:
            print("Claude API error: " + str(e))
            return None

    async def generate_with_openai(self, prompt: str, max_tokens: int = 2000) -> str:
        if not self.openai_key or self.openai_key == "your-key-here":
            return None
        
        try:
            async with httpx.AsyncClient() as client:
                response = await client.post(
                    "https://api.openai.com/v1/chat/completions",
                    headers={
                        "Authorization": f"Bearer {self.openai_key}",
                        "Content-Type": "application/json"
                    },
                    json={
                        "model": "gpt-3.5-turbo",
                        "max_tokens": max_tokens,
                        "messages": [{"role": "user", "content": prompt}]
                    },
                    timeout=60.0
                )
                data = response.json()
                if "choices" in data:
                    return data["choices"][0]["message"]["content"]
                else:
                    print("OpenAI API error: " + str(data))
                    return None
        except Exception as e:
            print("OpenAI API error: " + str(e))
            return None

    async def generate(self, prompt: str, max_tokens: int = 2000) -> str:
        result = None
        if self.anthropic_key and self.anthropic_key != "your-key-here":
            result = await self.generate_with_claude(prompt, max_tokens)
        if not result and self.openai_key and self.openai_key != "your-key-here":
            result = await self.generate_with_openai(prompt, max_tokens)
        if not result:
            result = self.generate_local(prompt)
        return result

    def generate_local(self, prompt: str) -> str:
        """Fallback: generate a basic report without external API."""
        return f"""# Research Report

## Summary
Based on the analysis of the provided sources, here are the key findings:

{prompt}

## Key Insights
- Multiple sources were analyzed to extract important entities and claims
- The knowledge graph shows connections between different topics
- Entity frequency analysis reveals the most mentioned subjects

## Conclusion
This report was generated from the ingested research data. For more detailed analysis, configure an LLM API key in the .env file.

---
*Generated by InsightGraph*
"""
